import React from 'react';
import { Upload, File as FileIcon, Download, RefreshCw, AlertCircle, CheckCircle, Trash2, Zap, Shield, FileSpreadsheet, Table, Layout, X } from 'lucide-react';
import * as XLSX from 'xlsx';
import html2pdf from 'html2pdf.js';

export default function ExcelToPdf() {
  const [file, setFile] = React.useState<File | null>(null);
  const [isProcessing, setIsProcessing] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);
  const [success, setSuccess] = React.useState(false);
  const [pdfBlob, setPdfBlob] = React.useState<Blob | null>(null);

  // Options
  const [pageSize, setPageSize] = React.useState('a4');
  const [orientation, setOrientation] = React.useState<'portrait' | 'landscape'>('portrait');
  const [sheetSelection, setSheetSelection] = React.useState<'all' | 'first'>('all');
  const [tableStyle, setTableStyle] = React.useState<'bordered' | 'clean'>('bordered');

  const formatBytes = (bytes: number, decimals = 2) => {
    if (bytes === 0) return '0 Bytes';
    const k = 1024;
    const dm = decimals < 0 ? 0 : decimals;
    const sizes = ['Bytes', 'KB', 'MB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(dm)) + ' ' + sizes[i];
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const selectedFile = e.target.files?.[0];
    if (selectedFile) {
      const extension = selectedFile.name.split('.').pop()?.toLowerCase();
      if (!['xls', 'xlsx'].includes(extension || '')) {
        setError('❌ Unsupported file type. Please upload an Excel file (.xls or .xlsx).');
        return;
      }
      if (selectedFile.size > 15 * 1024 * 1024) {
        setError(`❌ File too large (max 15MB). Current: ${formatBytes(selectedFile.size)}`);
        return;
      }
      setFile(selectedFile);
      setError(null);
      setSuccess(false);
      setPdfBlob(null);
    }
  };

  const escapeHtml = (str: any) => {
    if (!str) return '';
    return String(str).replace(/[&<>]/g, (m) => {
      if (m === '&') return '&amp;';
      if (m === '<') return '&lt;';
      if (m === '>') return '&gt;';
      return m;
    });
  };

  const sheetToHtml = (sheetData: any[][], sheetName: string, style: 'bordered' | 'clean', includeSheetTitle = true) => {
    if (!sheetData || sheetData.length === 0) return '';
    
    let html = '';
    if (includeSheetTitle) {
      html += `<h2 style="font-size: 18px; font-weight: bold; margin: 20px 0 10px 0; color: #0274be;">${escapeHtml(sheetName)}</h2>`;
    }
    
    const borderStyle = style === 'bordered' ? 'border: 1px solid #ddd;' : 'border: none;';
    const headerBg = style === 'bordered' ? '#f2f2f2' : '#e8f4f8';
    
    html += `<table style="width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 12px;">`;
    
    for (let i = 0; i < sheetData.length; i++) {
      html += `<tr>`;
      for (let j = 0; j < sheetData[i].length; j++) {
        const cellValue = sheetData[i][j] !== undefined && sheetData[i][j] !== null ? sheetData[i][j] : '';
        const isHeader = i === 0;
        const cellStyle = `${borderStyle} padding: 8px; text-align: left; ${isHeader ? `background-color: ${headerBg}; font-weight: bold;` : ''}`;
        html += `<td style="${cellStyle}">${escapeHtml(String(cellValue))}</td>`;
      }
      html += `</tr>`;
    }
    html += `</table>`;
    
    return html;
  };

  const convertToPdf = async () => {
    if (!file) return;

    setIsProcessing(true);
    setError(null);
    setSuccess(false);

    try {
      const data = await file.arrayBuffer();
      const workbook = XLSX.read(data, { type: 'array' });
      
      let htmlContent = `
        <div style="font-family: Arial, sans-serif; padding: 20px;">
          <h1 style="font-size: 24px; color: #0274be; margin-bottom: 20px;">${escapeHtml(file.name)}</h1>
      `;
      
      const sheetNames = workbook.SheetNames;
      const sheetsToProcess = sheetSelection === 'all' ? sheetNames : [sheetNames[0]];
      
      for (const sheetName of sheetsToProcess) {
        const worksheet = workbook.Sheets[sheetName];
        const sheetData = XLSX.utils.sheet_to_json(worksheet, { header: 1, defval: '' }) as any[][];
        
        if (sheetData && sheetData.length > 0) {
          htmlContent += sheetToHtml(sheetData, sheetName, tableStyle, sheetsToProcess.length > 1);
        } else {
          htmlContent += `<p><strong>${escapeHtml(sheetName)}</strong>: No data found</p>`;
        }
      }
      
      htmlContent += `
          <div style="margin-top: 30px; font-size: 10px; color: #999; text-align: center; border-top: 1px solid #eee; padding-top: 10px;">
            Generated by DocToolHubPK • Excel to PDF Converter
          </div>
        </div>
      `;

      const element = document.createElement('div');
      element.innerHTML = htmlContent;
      
      const opt = {
        margin: [0.5, 0.5, 0.5, 0.5],
        filename: file.name.replace(/\.(xls|xlsx)$/i, '') + '.pdf',
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: { scale: 2, useCORS: true, logging: false },
        jsPDF: { unit: 'in', format: pageSize, orientation: orientation }
      };

      // @ts-ignore - html2pdf types might be missing
      const blob = await html2pdf().set(opt).from(element).outputPdf('blob');
      setPdfBlob(blob);
      setSuccess(true);
    } catch (err: any) {
      console.error('Conversion error:', err);
      setError(`❌ Conversion failed: ${err.message}`);
    } finally {
      setIsProcessing(false);
    }
  };

  const downloadPdf = () => {
    if (!pdfBlob || !file) return;
    const url = URL.createObjectURL(pdfBlob);
    const link = document.createElement('a');
    link.href = url;
    link.download = file.name.replace(/\.(xls|xlsx)$/i, '') + '.pdf';
    link.click();
    URL.revokeObjectURL(url);
  };

  const reset = () => {
    setFile(null);
    setPdfBlob(null);
    setSuccess(false);
    setError(null);
  };

  return (
    <div className="space-y-8">
      <div className="bg-white premium-card rounded-3xl border border-gray-200/70 p-6 md:p-8 mb-12 shadow-sm w-full">
        {/* UPLOAD AREA */}
        {!file ? (
          <div className="border-2 border-dashed border-gray-200 rounded-2xl p-6 text-center cursor-pointer hover:border-[#0274be] transition bg-gray-50/20 mb-6 relative">
            <input 
              type="file" 
              accept=".xls,.xlsx,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" 
              onChange={handleFileChange} 
              className="absolute inset-0 opacity-0 cursor-pointer" 
            />
            <div className="flex flex-col items-center gap-2">
              <div className="bg-blue-50 p-3 rounded-full">
                <FileSpreadsheet className="h-7 w-7 text-[#0274be]" />
              </div>
              <p className="text-lg font-medium text-gray-800">Drag & drop Excel file or <span className="text-[#0274be] underline underline-offset-2 font-semibold">browse</span></p>
              <p className="text-sm text-gray-500">Supports .XLS and .XLSX • max 15MB</p>
            </div>
          </div>
        ) : (
          <div className="mb-6">
            <div className="flex items-center justify-between bg-gray-50 p-4 rounded-xl border border-gray-200">
              <div className="flex items-center space-x-3 truncate">
                <div className="bg-blue-50 p-2 rounded-lg">
                  <FileIcon className="h-5 w-5 text-[#0274be]" />
                </div>
                <div className="text-left">
                  <p className="font-medium text-gray-800 truncate max-w-[200px] md:max-w-xs">{file.name}</p>
                  <p className="text-xs text-gray-500">{formatBytes(file.size)}</p>
                </div>
              </div>
              <button 
                onClick={reset}
                className="text-gray-500 hover:text-[#0274be] bg-white border border-gray-300 px-4 py-2 rounded-lg text-sm font-medium flex items-center gap-1 transition"
              >
                <X className="h-4 w-4" />
                Reset
              </button>
            </div>
          </div>
        )}

        {/* CONTROLS */}
        {file && (
          <div className="space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label className="text-sm font-medium text-gray-700 block mb-2">Page size</label>
                <select 
                  value={pageSize}
                  onChange={(e) => setPageSize(e.target.value)}
                  className="w-full p-2.5 border border-gray-300 rounded-xl text-sm focus:ring-1 focus:ring-[#0274be] focus:border-[#0274be] outline-none bg-white"
                >
                  <option value="a4">A4</option>
                  <option value="letter">Letter</option>
                  <option value="legal">Legal</option>
                </select>
              </div>
              <div>
                <label className="text-sm font-medium text-gray-700 block mb-2">Orientation</label>
                <select 
                  value={orientation}
                  onChange={(e) => setOrientation(e.target.value as any)}
                  className="w-full p-2.5 border border-gray-300 rounded-xl text-sm focus:ring-1 focus:ring-[#0274be] focus:border-[#0274be] outline-none bg-white"
                >
                  <option value="portrait">Portrait</option>
                  <option value="landscape">Landscape</option>
                </select>
              </div>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label className="text-sm font-medium text-gray-700 block mb-2">Sheet selection</label>
                <select 
                  value={sheetSelection}
                  onChange={(e) => setSheetSelection(e.target.value as any)}
                  className="w-full p-2.5 border border-gray-300 rounded-xl text-sm focus:ring-1 focus:ring-[#0274be] focus:border-[#0274be] outline-none bg-white"
                >
                  <option value="all">All sheets</option>
                  <option value="first">First sheet only</option>
                </select>
              </div>
              <div>
                <label className="text-sm font-medium text-gray-700 block mb-2">Table style</label>
                <select 
                  value={tableStyle}
                  onChange={(e) => setTableStyle(e.target.value as any)}
                  className="w-full p-2.5 border border-gray-300 rounded-xl text-sm focus:ring-1 focus:ring-[#0274be] focus:border-[#0274be] outline-none bg-white"
                >
                  <option value="bordered">Bordered</option>
                  <option value="clean">Clean (no borders)</option>
                </select>
              </div>
            </div>

            <div className="flex flex-col sm:flex-row gap-4">
              <button 
                onClick={convertToPdf}
                disabled={isProcessing}
                className="bg-[#0274be] text-white font-semibold px-8 py-3.5 rounded-xl shadow-md hover:shadow-lg disabled:opacity-50 disabled:cursor-not-allowed transition flex items-center justify-center gap-2 flex-1"
              >
                {isProcessing ? (
                  <>
                    <RefreshCw className="h-5 w-5 animate-spin" />
                    <span>Converting...</span>
                  </>
                ) : (
                  <>
                    <RefreshCw className="h-5 w-5" />
                    <span>Convert to PDF</span>
                  </>
                )}
              </button>
              <button 
                onClick={downloadPdf}
                disabled={!pdfBlob || isProcessing}
                className="bg-white border-2 border-[#0274be] text-[#0274be] font-semibold px-6 py-3.5 rounded-xl hover:bg-[#0274be]/5 transition disabled:opacity-40 disabled:border-gray-300 disabled:text-gray-400 flex items-center justify-center gap-2 flex-1 sm:flex-none"
              >
                <Download className="h-5 w-5" />
                Download PDF
              </button>
            </div>
          </div>
        )}

        {/* STATUS */}
        {(error || success) && (
          <div className={`mt-5 text-sm p-3 rounded-xl flex items-center gap-2 ${error?.startsWith('❌') || error?.startsWith('⚠️') ? 'bg-red-100 text-red-700' : success ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-700'}`}>
            {success ? <CheckCircle className="h-5 w-5" /> : error?.startsWith('❌') ? <AlertCircle className="h-5 w-5" /> : null}
            <span>{success ? `✅ Conversion complete! Click Download PDF.` : error}</span>
          </div>
        )}
      </div>

      <div className="bg-white py-10 border-t border-gray-100 w-full">
        <h2 className="text-2xl md:text-3xl font-bold text-center text-gray-900 mb-12">Why choose DocToolHubPK?</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          <FeatureCard 
            icon={<Zap className="h-6 w-6 text-[#0274be]" />}
            title="Fast conversion"
            description="Convert Excel to PDF in seconds, client‑side."
          />
          <FeatureCard 
            icon={<Table className="h-6 w-6 text-[#0274be]" />}
            title="Preserve tables"
            description="Maintains all data, formulas, and structure."
          />
          <FeatureCard 
            icon={<Shield className="h-6 w-6 text-[#0274be]" />}
            title="100% secure"
            description="No upload — your Excel file stays on your device."
          />
          <FeatureCard 
            icon={<Layout className="h-6 w-6 text-[#0274be]" />}
            title="Multi-sheet support"
            description="Convert all sheets or select specific ones."
          />
        </div>
      </div>
    </div>
  );
}

function FeatureCard({ icon, title, description }: { icon: React.ReactNode, title: string, description: string }) {
  return (
    <div className="bg-gray-50/80 p-6 rounded-2xl border border-gray-100 shadow-sm hover:shadow-md transition">
      <div className="bg-blue-50 w-12 h-12 rounded-xl flex items-center justify-center mb-4">
        {icon}
      </div>
      <h3 className="text-lg font-semibold text-gray-800 mb-2">{title}</h3>
      <p className="text-sm text-gray-600 leading-relaxed">{description}</p>
    </div>
  );
}
